### ISSUE TITLE
readline 7 revisions needed

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/homebrew-science#4367]
- [x] homebrew/science/gap #4368
- [x] homebrew/science/gnudatalanguage #4369
- [x] homebrew/science/nest #4370  
- [x] homebrew/science/nexusformat #4371
- [x] homebrew/science/octave #4327
- [x] homebrew/science/pspp #4372
- [x] homebrew/science/qcl #4373
- [x] homebrew/science/r #4374
- [x] homebrew/science/shogun #4375
- [x] homebrew/science/symphony #4376

**Comment by jhhinrichsen** [comment]
tig is broken too
