### ISSUE TITLE
formulae using deprecated names

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/homebrew-science#5455]
- [x] gnudatalanguage.rb:22:  depends_on "homebrew/versions/hdf4" => :optional (#5479)
- [x] matplotlib.rb:72:  depends_on "homebrew/dupes/tcl-tk" => :optional (#5480)
- [x] oce.rb:26:    depends_on "homebrew/dupes/tcl-tk"  (#5478)
- [x] opencascade.rb:30:    depends_on "homebrew/dupes/tcl-tk" (#5481)
- [x] pocl.rb:16:    depends_on "homebrew/versions/llvm34" (#5482)
- [ ] pymol.rb:17:  depends_on "homebrew/dupes/tcl-tk" => ["with-threads", "with-x11"] (#5483)
- [x] therion.rb:18:  depends_on "homebrew/dupes/tcl-tk" if MacOS.version >= :sierra (#5484)

**Comment by ilovezfs** [comment]
@iMichka btw I think as part of this therion's bottling can be turned back on.

**Comment by ilovezfs** [comment]
Closing since the only one left is `pymol` for which there is now a PR: #5483 

Thanks @iMichka
