### ISSUE TITLE
Revisions for jpeg 9 needed

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/homebrew-science#6075]
- [x] astrometry-net (broken anyway #6079)
- [x] opencv
- [x] dlib
- [x] enblend-enfuse
- [x] hdf4
- [x] insighttoolkit
- [x] lammps
- [x] mathgl
- [x] nexusformat
- [x] opencv3
- [x] openimageio
- [x] paraview
- [x] pcl
- [x] pillow
- [x] siril
- [ ] statismo (broken anyway #5916)
- [x] sumo
- [ ] therion (broken anyway #5917)
- [x] vigra
- [x] visp
- [x] vtk
- [x] wxmaxima
- [x] xfig

Not sure about these since they depend on jpeg but aren't linked to it:
- [x] blast (remove jpeg dependency: #6157)
- [x] openalpr (openalpr needs a revision bump for opencv, making a note there #6186)

**Comment by iMichka** [comment]
Made a comment for the two last ones which were unclear. All done, closing here.
